stages:
  - build

variables:
  NODE_ENV: 'development'
  DATABASE_URL: 'postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}'

before_script:
  - echo "Running before_script"
  - apt-get update -qy
  - apt-get install -y python3 python3-pip
  - pip3 install pipenv

build_application:
  stage: build
  tags:
    - docker
    - konsulent
    - linux
  script:
    # Frontend build
    - npm install
    - npm run build
    - cd ..
    # Backend build
    - cd backend
    - pipenv install --dev
    - cd ..
  artifacts:
    paths:
      - frontend/dist
