stages:
  - build
  - test

variables:
  NODE_ENV: "development"
  DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"

build_application:
  stage: build
  image: node:20
  tags:
    - linux
    - konsulent
    - docker
  only:
    - merge_requests
    - main
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm
      - node_modules/
    policy: pull-push
  before_script:
    - echo "Running before_script"
    - npm ci --cache .npm --no-optional --prefer-offline
  script:
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: 1 week # Adjust as needed

test_backend:
  stage: test
  image: python:3.8
  tags:
    - linux
    - konsulent
    - docker
  before_script:
    - echo "Setting up the environment"
    - pip install pipenv
    - cd backend
    - pipenv install --dev
  script:
    - pipenv run pytest
  artifacts:
    when: always
    paths:
      - backend/tests
    expire_in: 1 week
