stages:
  - build

variables:
  NODE_ENV: 'development'

build_application:
  stage: build
  image: node:14
  tags:
    - linux
    - konsulent
    - docker
  only:
    - merge_requests
    - main
  cache:
    paths:
      - .npm/
      - node_modules/
      - cache/
    policy: pull-push
  before_script:
    - echo "Running before_script"
    - npm ci --cache .npm --no-optional --prefer-offline
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist
