stages:
  - build

variables:
  NODE_ENV: 'development'

build_application:
  stage: build
  image: node:20
  tags:
    - linux
    - konsulent
    - docker
  only:
    - merge_requests
    - main
  before_script:
    - echo "Running before_script"
    - npm install
    - npm update
  script:
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: 1 week  # Adjust as needed
