variables:
  NODE_ENV: 'development'
  DATABASE_URL: 'postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}'

stages:
  - build

build_application:
  image: gitlab.geomatikk.no:5050/geomelding/docker-ci-images/node-linux-cordova:latest
  tags:
    - linux
    - konsulent
    - docker
  only:
    - merge_requests
    - main
  cache:
    paths:
      - .npm/
      - node_modules/
      - backend/.pipenv/
      - cache/
    policy: pull-push
  before_script:
    - echo "Running before_script"
    - npm ci --cache .npm --no-optional --prefer-offline
  script:
    # Frontend build
    - npm install
    - npm run build
    # Backend build
    - cd backend
    - pip install pipenv
    - pipenv install --dev
    - cd ..
  artifacts:
    paths:
      - dist
