test_frontend:
  stage: test
  image: gitlab.geomatikk.no:5050/geomelding/docker-ci-images/node-linux-cordova:latest
  tags:
    - linux
    - konsulent
    - docker
  only:
    - merge_requests
    - main
  before_script:
    - echo "Running before_script. Installing dependencies"
    - npm ci --include=optional --cache .npm --prefer-offline
  script:
    - echo "Running tests with coverage"
    - npm run test:ci
  artifacts:
    when: always
    paths:
      - coverage/
      - coverage/gitlab-junit/report.xml
      - coverage/sonar-junit/report.xml
    expire_in: 1 week
