variables:
  NODE_ENV: 'development'
  CHROME_BIN: "/usr/bin/google-chrome"

stages:
  - build
  - test

build_application:
  stage: build
  image: node:latest
  tags:
    - linux
    - konsulent
    - docker
  only:
    - merge_requests
    - main
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm
      - node_modules/
    policy: pull-push
  before_script:
    - echo "Running before_script"
    - apt-get update && apt-get install -y wget gnupg
    - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
    - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
    - apt-get update && apt-get install -y google-chrome-stable
    - npm ci --include=optional --cache .npm --prefer-offline
  script:
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: 1 week # Adjust as needed

test_frontend:
  stage: test
  image: node:latest
  tags:
    - linux
    - konsulent
    - docker
  before_script:
    - echo "Running before_script"
    - apt-get update && apt-get install -y wget gnupg
    - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
    - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
    - apt-get update && apt-get install -y google-chrome-stable
    - npm ci --include=optional --cache .npm --prefer-offline
  script:
    - echo "Running tests with coverage"
    - npm run test:ci
  artifacts:
    when: always
    paths:
      - coverage/
    expire_in: 1 week
  dependencies:
    - build_application
