test_frontend:
  stage: test
  image: trion/ng-cli-karma
  tags:
    - linux
    - konsulent
    - docker
  only:
    - merge_requests
    - main
  before_script:
    - echo "Running before_script. Installing dependencies"
    - npm ci --include=optional --cache .npm --prefer-offline
  script:
    - echo "Running tests with coverage"
    - npm run test:ci
    - echo "Killing any leftover processes"
    - pkill -f karma || true
  artifacts:
    when: always
    paths:
      - coverage/
    expire_in: 1 week
  #dependencies:
  #  - build_frontend
