test_frontend:
  stage: test
  image: trion/ng-cli-karma
  tags:
    - linux
    - konsulent
    - docker
  script:
    - echo "Installing dependencies"
    - npm ci --include=optional
    - echo "Running tests with coverage"
    - npm run test:ci
  artifacts:
    when: always
    paths:
      - coverage/
    expire_in: 1 week
  #dependencies:
   # - build_frontend
  after_script:
    - echo "Checking coverage"
    - COVERAGE=$(jq '.total.statements.pct' coverage/cable_network_visualization/lcov-report/index.html | sed -n 's/.*<span class="strong"> \([0-9]*\).*/\1/p')
    - echo "Test coverage is $COVERAGE%"
    - if [ "$COVERAGE" -lt 80 ]; then echo "Coverage below threshold"
