variables:
  NODE_ENV: 'development'
  CHROME_BIN: '/usr/bin/google-chrome'

stages:
  - build
  - test

build_frontend:
  stage: build
  image: node:latest
  tags:
    - linux
    - konsulent
    - docker
  only:
    - merge_requests
    - main
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm
      - node_modules/
    policy: pull-push
  before_script:
    - echo "Running before_script"
    - apt-get update && apt-get install -y ca-certificates
    - npm install -g @angular/cli
    - npm ci --include=optional --cache .npm --prefer-offline
  script:
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: 1 week
