stages:
  - lint

lint_application:
  stage: lint
  image: node:18
  tags:
    - linux
    - konsulent
    - docker
  only:
    - merge_requests
    - main
  script:
    - npm ci --include=optional --cache .npm --prefer-offline
    - npm run lint
    - npm run format
  artifacts:
    paths:
      - src/**/*.{js,ts,html,css,scss}
    expire_in: 1 week # Adjust as needed
