stages:
  - lint

lint_application:
  stage: lint
  image: node:latest
  tags:
    - linux
    - konsulent
    - docker
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm
      - node_modules/
    policy: pull-push
  script:
    - npm ci --cache .npm --no-optional --prefer-offline
    - npm run lint
    - npm run format:check
