stages:
  - lint

lint_application:
  stage: lint
  image: node:18
  tags:
    - linux
    - konsulent
    - docker
  only:
    - merge_requests
    - main
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm
      - node_modules/
    policy: pull-push
  before_script:
    - echo "Running before_script"
    - npm ci --include=optional --cache .npm --prefer-offline
  script:
    - npm run lint
    - npx prettier . --write
  artifacts:
    paths:
      - src/**/*.{js,ts,html,css,scss}
    expire_in: 1 week # Adjust as needed
